# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.cache/wt [current_project]
set_property parent.project_path C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/char8x16_rom.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/core_alu.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/core_bus_wrapper.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/core_id_stage.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/core_instr_bus_adapter.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/core_regfile.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/core_top.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/dual_read_port_ram_32x32.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/instr_rom.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/isp_uart.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/naive_bus.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/naive_bus_router.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/new/pout_led.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/ram.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/ram128B.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/ram_bus_wrapper.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/soc_top.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/uart_rx.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/uart_tx_line.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/user_uart_tx.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/vga_char_86x32.sv
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/imports/RTL/video_ram.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/new/pout_seg.v
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/new/seg.v
  C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/sources_1/new/EGOR035_HDRVSoC_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/constrs_1/new/EGOR035_HDRVSoC_top.xdc
set_property used_in_implementation false [get_files C:/Users/WTse_/Desktop/RISC-V_Core_On_FPGA/HDRVSoC-Xilinx/hardware/Vivado_top/EGOR035_HDRVSoC_top/EGOR035_HDRVSoC_top.srcs/constrs_1/new/EGOR035_HDRVSoC_top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top EGOR035_HDRVSoC_top -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef EGOR035_HDRVSoC_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file EGOR035_HDRVSoC_top_utilization_synth.rpt -pb EGOR035_HDRVSoC_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
